Ritika-Das/Data_Structures_and_Algorithms.github.io

Python/Heap_Sort.py
Added Heap Sort implemented with python.
- New Script
=> Added Heap_Sort

Python/selectionSort.py
Before it would swap 100 times if there were 100 numbers to sort, every time,
no exceptions. Now it will only swap when needed, which will result in fewer swaps.
=> Optimize selection sort

C++/Merge_sort.cpp
=> Added Merge_sort Algo in C++

Python/hackerrank_encryption.py
Solution for hackerrank problem  named as 'Encryption'
=> encryption solution

Python/Exponential_Search.py, Python/Jump_Search.py
Added Exponential Search and Jump Search implemented with python.
-New Scripts
=> Added New Searching Algorithms

C++/Floyd_Warshall_Algorithm.cpp
For solving the All Pairs Shortest Path problems.
=> Added Floyd Warshall Algorithm

C/Quiz_game.c
I hope you will accept my contribution...
=> Quiz Game using C

Special Programs/1.c, Special Programs/10.c, Special Programs/2.c, Special Programs/3.c, Special Programs/4.c, Special Programs/5.c, Special Programs/6.c, Special Programs/7.c, Special Programs/8.c, Special Programs/9.c
Added some programs like sorting, merging two sorted arrays, and duplicate removal from array C programs.
=> Add some new programs

C/BucketSort.c
Bucket or Bin Sort in C language on array with randomized values. Outputs unsorted and sorted arrays and number of comparisons and assignments performed.
Happy Hacktoberfest!
=> Add Bucket (Bin) Sort in C

Matlab/HighValueSearch.m
Matlab code that does a linear search to find the higher value in an array.
=> HighValueSearch.m

C++/interpolation search.cpp
Interpolation Search is a algorithm where we use a mathematical formula to guess the position where that key might exist. The array or list must be sorted.
Time Complexity - O(n).
=> Added Interpolation Search Technique

C++/Depth_first_search.cpp
Implemented depth first search for a graph.
=> Depth First Search algorithm added

C++/Binary_Exponentiation.cpp
Wrote a recursive function for binary exponentiation.
=> Binary Exponentiation

C++/LeftRecursion.cpp
I have added a cpp file that will take input as production then gives left recursive converted production as output.
=> Left Recursion of a production program in cpp

C++/CountingSort.cpp
=> Added CountingSort.cpp

C++/insertionsort.cpp
=> added insertionsort

Python/chineseprob.py
Classic ancient Chinese puzzle solution:
We count 35 heads and 94 legs among the chickens and rabbits in a farm. How many rabbits and how many chickens do we have?
=> Added Chinese Problem

JAVA/ECC.java
ECC is a popular asymmetric cryptographic algorithm.
=> Adding ECC implemented Java

C/knapsack_dynamic.c
i have created c program for knapsack problem solved dynamically.
=> Created knapsack_dynamic.c

C/circular_queue.c
i have added a c program for circular queue using linked list data structure. In program rear and front pointers are used for accessing linked list as queue.
=> Created circular_queue.c
